// template-static/vue2/src/pages/Home.vue
<template>
  <div>
    <img alt="Vue logo" src="../assets/logo.png" />
    <div>
      <router-link to="/about">About page</router-link>
    </div>
    <HelloWorld msg="Welcome to Your Vue.js App" />
  </div>
</template>

<script>
import HelloWorld from '../components/HelloWorld.vue';
export default {
  components: {
    HelloWorld,
  },
};
</script>

<style></style>

// templates/react-static/src/pages/home.js
import React from 'react';
import { Link } from 'react-router-dom';
import logo from '../logo.svg';

const Home = () => {
  return (
    <header className="app-header">
      <img src={logo} className="app-logo" alt="logo" />
      <Link className="app-link" to="/about">
        About
      </Link>
      <a className="app-link" href="https://docs.arcblock.io/abtnode/" target="_blank" rel="noopener noreferrer">
        Learn Blocklet
      </a>
    </header>
  );
};

export default Home;
